### ISSUE TITLE
Objective is none 

### ISSUE THREAD

**Issue by pbelmann** [cdanielmachado/reframed#1]
Hi Daniel,

I build multiple models using carveme and I wanted to use FBA in order to view flux distribution and escher maps.
However viewing the solution it seems that the Objective is `none` and Status is `unbounded`.
Does it mean that the model is wrongly build?
Could you give any recommendations on how to proceed?

**Comment by cdanielmachado** [comment]
Did you define a growth medium ?

**Comment by pbelmann** [comment]
No

**Comment by cdanielmachado** [comment]
The model you are using probably doesn't come with a growth medium pre-defined, you need to define one yourself.

 You can find examples here: https://reframed.readthedocs.io/en/latest/simulation.html#using-environments
