### ISSUE TITLE
questions about Environment class

### ISSUE THREAD

**Issue by amarsh26** [cdanielmachado/reframed#17]
For in iML1515 model, when I set the environment without a carbon or phosphorus source as follows, Environment.from_compounds(["o2", "nh4"]), I receive a biomass of Objective: 0.531523706409258
Status: Optimal.
Is this the expected result? If so, where is it getting a carbon and phosphorus source? Also, how do I determine the default media your tool is using for FBA?

Thanks,
Alexis

**Comment by cdanielmachado** [comment]
Hi Alexis,

That's because the Environment class will not change the default bounds in the model for compounds that are not specified in the environment.

You can do:

```
env = Environment.from_compounds(["o2", "nh4"]).apply(model, inplace=False)
sol = FBA(model, constraints=env)
```

or 


```
Environment.from_compounds(["o2", "nh4"]).apply(model, inplace=True)
sol = FBA(model)
```

**Comment by amarsh26** [comment]
Thanks so much for your help!
