### ISSUE TITLE
Models not growing anymore after update

### ISSUE THREAD

**Issue by urihs** [cdanielmachado/reframed#2]
Hi,

First of all, thank you for creating and updating this software.

My issue started after updating CarveMe to version 1.5.0 and ReFramed to version 1.2.1. I re-run several scripts I had, which implied creating new CarveMe models from certain protein genomes and then checking their growth rate with ReFramed. I checked their growth in simple variations of the M9 medium - which I had been using before - and without any gap-filling. The CarveMe calls are like this:

`carve dir/file -u grampos -o outputfile`

And the ReFramed in-code call is the following:

```
  media_db = load_media_db(mediadb, compound_col="compound")
  
  init_env = Environment.from_compounds(media_db[medium])
  
  for f in model_filepaths:
  
      model = load_cbmodel(f,flavor="fbc2")
  
      init_env.apply(model)
  
      solution = FBA(model,   objective="Growth", get_values=False)    
  
      print(solution)
```

Before the updates, most of my CarveMe fbc2 models grew on these media according to ReFramed. However, now only a few are capable to grow according to ReFramed.

I would assume this is because the new models are revealing more accurate info, but I know from wet-lab experiments that the modelled organisms are actually capable to grow on these media. I noticed the SBML files themselves include new fields. Should I modify my code in some way? Is it possible that there is some kind of new format incompatibility or bug on CarveMe or ReFramed?

Thank you again for dedicating so much time to these packages

Cheers,
Silvia

**Comment by cdanielmachado** [comment]
Hi Silvia,

I would say that if your models were growing in M9 without gap-filling for M9 you were very lucky... :) If you know that a species grows in a given medium it is always best to provide that information during the reconstruction.

That being said, it is strange if the results change too much. Can you try building your models again, this time gap-filling for M9, and checking how many gap-filling reactions are included? 

If only a few reactions are included it's ok, but if they are too many, then something is wrong, and we need to dig further.

So I think this is a problem related to CarveMe, not reframed. But anyway, something I would recommend is that you use `flavor='bigg'` when loading the models. This shouldn't change much (only affects the way sink reactions are treated), but it doesn't hurt to try.
