### ISSUE TITLE
Check for fbc plugin

### ISSUE THREAD

**Issue by JosuaCarl** [cdanielmachado/reframed#3]
The method load_metabolite in io/sbml.py  < load_metabolite(species, flavor=None, load_metadata=True) > does not check whether the species has the fbc plugin enabled. This produced an AttributeError: "None-Type" object has no attribute 'isSetChemicalFormula', if the Plugin is not enabled.

Suggestions:
If this is desired behavior, please add an appropriated error/warning message.

If not, please add a check < if species.isPackageEnabled("fbc"): > before calling iSetChemicalFormula() or isSetCharge()

**Comment by cdanielmachado** [comment]
Please use flavor='cobra' if the model is not using FBC

**Comment by JosuaCarl** [comment]
You are completely right, I did pass --cobra into carveme, which then passes it on, but it turns out it does only do so for the specified model. Not however for the given universe (grampos in my case). This however is an issue for carveme, I'm gonna close this report and do another one over there. 

Thank you for your quick reply.
